### ISSUE TITLE
Mistake: Imperativo (voi) volere !!!!

### ISSUE THREAD

**Issue by Odysseus789** [boolbag/Anki-Goodies#1]
![fehl](https://user-images.githubusercontent.com/63735514/87252895-e081a800-c476-11ea-83ba-ff6529e1568a.PNG)
  

SHOULD BE volete !

Noticed this mistake because it didnt fit the italian conjugation pattern, then checked online, btw epic tool to see hole conjugation table at once is Babbles
https://de.bab.la/konjugieren/italienisch/volere

**Comment by boolbag** [comment]
No, it's an exception, it's _vogliate_. 
Well-known exceptions of the second person of the imperative: avere→abbiate, essere→siate, sapere→sappiate, volere→vogliate
The automatic conjugation tools don't know about exceptions.

Several references to more trustworthy sources [here](https://www.reddit.com/r/italianlearning/comments/4z927d/volete_o_vogliate/).

**Comment by Odysseus789** [comment]
thank you for telling me!
