### ISSUE TITLE
Hierarchical tag structure with single top-level tag

### ISSUE THREAD

**Issue by benroot** [boolbag/Anki-Goodies#2]
I want to bring up the idea of using a hierarchical tag structure for the Ultimate Spanish Conjugation deck. There is an excellent Addon called Hierarchical tags 2 (and an older one for Anki < 2.1) which lets sub-tags be folded into other tags in the card browser. This makes it much easier to use the Anki Browser to navigate to and select specific tags. 

I made a mockup of what it would look like with hierarchical tags:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/34732/102796360-245ccf80-437c-11eb-9e5e-68441d7132b7.png">

Here is what a single tag would turn into:
`UltimateSpanishConjugation::1-subject::yo`

Note: Anki does not allow spaces in tags so a common convention is to use '-' hyphen to separate words in multi-word tags.

 I could try to submit a pull request if you have the raw data somewhere in CSV/TSV form I could modify programmatically.

P.S. Thank you for creating this deck! I think it looks excellent and I cannot wait to start using it.

**Comment by wyohm** [comment]
I believe [Ultimate Spanish Conjugation {{Cloze}}.4anki](https://github.com/boolbag/Anki-Goodies/blob/master/Decks/Spanish/source/Ultimate%20Spanish%20Conjugation%20%7B%7BCloze%7D%7D.4anki) is what you're looking for.

Personally, I don't like the digits in the tags (prefer "subject" to "1-subject"). Unless there's a good reason for that I'm not seeing?

**Comment by benroot** [comment]
Fair point, re: the numbers -- they are kind of a kludge to prioritize the tags since the sorting in Anki is just alphabetical. I made pull request without numbers. Check it out and see how it looks: #3

**Comment by benroot** [comment]
I realized maybe I should leave this open in case anybody else had thoughts!

**Comment by blueputty01** [comment]
I was trying to organize the tags myself, but I'm glad I found this before I finished. This made it much easier! Thanks for sharing, @benroot!

**Comment by boolbag** [comment]
Thanks for the discussion guys. Sounds like you've found a solution you're happy with, closing.
