### ISSUE TITLE
Possible to add "type answer" to the cards? 

### ISSUE THREAD

**Issue by jarodise** [boolbag/Anki-Goodies#4]
Hi, first of all, thanks for creating such an incredible deck. 

This is not so much of an issue, but rather a feature request. 

When using Anki I often prefer to type the answer, I feel by typing it out it helps me to memorize better. 

normally it is fairly easy to add {{type:xxx}} in the card editing interface to create the "type answer" set up, however with the unique card setting of your deck, I find it rather hard to do this. 

ideally I would like to type in the answer(in this case the conjugated verb) and then when the back is flipped, the typed answer is cross checked with the correct answer tell me whether I am right or wrong. 

It would be really great if you could enlighten me on how to achieve this with this deck, thanks!

**Comment by otsegun** [comment]
I came here to request this feature also. What a fantastic deck you've created and thank for the work. 
I hope that you will consider implementing the typing in answer feature. 
Thanks

**Comment by jarodise** [comment]
> I came here to request this feature also. What a fantastic deck you've created and thank for the work.
> I hope that you will consider implementing the typing in answer feature.
> Thanks

Hi, I actually found another deck that's based on the similar principles and offers type answer function, maybe you would like to give it a try :  
link: https://ankiweb.net/shared/info/383891389

**Comment by otsegun** [comment]
Thanks @jarodise. I know of this deck and I already use it (and like it also). 
But this deck is better optimized and shorter I believe. My plan is actually to take a look at the deck you linked and see how they implemented their type in answer and checking in order to try to modify and implement it in this deck.

**Comment by boolbag** [comment]
Sorry for the lack of response, guys. 
If you find a change that works for you with respect to a whole card, send it to me and I'll look at generating a different version of the deck. Please look at in [this folder](https://github.com/boolbag/Anki-Goodies/tree/master/Decks/Spanish/source), open the deck's generated source
Ultimate Spanish Conjugation {{Cloze}}.4anki

and send me a BEFORE / AFTER version of a single card.

For instance, BEFORE:
c9b07a40-e422-41a6-bb22-2a78aefbdfdf;→ En el futuro, →<br><br><span class="cloze_pronoun">yo</span> <span class="sp_verb">{{c1::seré::…ser…}}</span> <span class="sp_hint">(consciente de ello)</span>;;<span class="SECTION_regularity"><br>The form <span class="notes_sp_form">seré</span> is <span class="note_feature">regular</span>.</span><br><span class="dle_conj"><a href="https://dle.rae.es/ser?m=form#conjugacion">ser</a></span> : extreme irregularity, #10 in the deck out of 59 dissonant verbs, 41 counts (74%)<span class="SECTION_family"><br><span class="note_feature">Unique verb.</span> The DLE has no other verb with this set of conjugation and spelling patterns.</span>;ends_in_er extreme_irregularity futuro irregular_verb regular_form ser yo

Closing now but feel free to reopen.
