### ISSUE TITLE
Manual - Images don't load, host bad SSL cert.

### ISSUE THREAD

**Issue by DreamingIntoTheVoid** [boolbag/Anki-Goodies#5]
The manuals images don't load for me in the current build of Firefox/Chrome.

Visiting one of the images directly gives the following error:

> Web sites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for b.yu8.us. The certificate is only valid for the following names: cloudfront.net, *.cloudfront.net
>  
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by boolbag** [comment]
Thank you, I think that's fixed. Feel free to reopen.
