### ISSUE TITLE
expresiones de tiempo + GERUNDIO

### ISSUE THREAD

**Issue by pstargaryen** [boolbag/Anki-Goodies#6]
En el deck, hay cartas que están incorrectas, con relación a expresión AHORA MISMO, el cual está pediendo para conjugar en el presente de indicativo, sin embargo, tenemos que conjugar en el presente continuo. SER + GERUNDIO.

⊙ Ahora mismo, ⊙

nosotros {{c1::pudrimos | podrimos::…pudrir…}} (al profesor)

La forma correcta sería: Ahora mismo nosotros estamos pudriendo al profesor.

Yo puedo estar errado en relación con esto, pero no veo sentido el uso del verbo PUDRIR en esta oración, hasta donde sé, esto significa "TO ROT".

**Comment by boolbag** [comment]
> no veo sentido el uso del verbo PUDRIR en esta oración

Mira [esto](https://www.diccionarios.com/diccionario/espanol/pudrir). Un fragmento:
2  Causar una persona o una cosa enfado o inquietud a otra .
    EJEMPLO:  pudre a su hermano con sus impertinencias; se pudre por dentro de impaciencia.
