### ISSUE TITLE
[Italian Deck] Tag for card 00003 incorrect

### ISSUE THREAD

**Issue by doolio** [boolbag/Anki-Goodies#9]
Firstly, excellent deck. 

Using this site linked from your manual it seems this card has an incorrect tag. I believe it should be tagged `infinito_passato` not `participio_passato`.

https://www.italian-verbs.com/italian-verbs/conjugation.php?parola=avere

However, considering your argument not to include compound conjugations in the deck shouldn't this card read *avuto* rather than *avere avuto* and thus the current tag would be correct. This way all compound conjugations that use *avuto* are excluded as you intended.

One minor point on your manual it states to start week 1 with `essere` yet the deck starts with the `avere` cards. Or maybe that was intentional to see if people actually read your manual as advised ;).

**Comment by doolio** [comment]
Any thoughts on the above?

**Comment by boolbag** [comment]
Thank you for your kind comments.

> shouldn't this card read avuto rather than avere avuto

Italian verbs use different auxiliary verbs: avere avuto vs. essere vissuto
Hence the inclusion of the auxiliary.

The learning point on this card is avuto, which is a participio passato.
I understand the confusion.

Regarding week 1, it's a bug in the manual. Not sure why. Just fixed it. Thank you for reporting.

**Comment by doolio** [comment]
> The learning point on this card is avuto, which is a participio passato.
> I understand the confusion.

Thanks for the clarification.
